### ISSUE TITLE
Error setup.py at line 6

### ISSUE THREAD

**Issue by bouroo** [isidentical/perf#1]
I try `pip install perf`
TypeError: coercing to Unicode: need string or buffer, PosixPath found
So, I workaround `with open(current_dir / "README.md", encoding="utf-8") as f:` with
`with open(str(current_dir / "README.md")) as f:` but you may have better solution for this issue.

**Comment by isidentical** [comment]
Which version of python are you using?

**Comment by bouroo** [comment]
Python 2.7.5
CentOS Linux release 7.6.1810 (Core)

**Comment by isidentical** [comment]
I am only supporting python 3.7+

**Comment by bouroo** [comment]
Oh. Thx for your fast response. I found this issuse from install CyberPanel that require perf==0.1 but they use python 2.7 OK. I'll discuss with them how to fix there promblem.

**Comment by isidentical** [comment]
The perf module you want to use renamed as pyperf, FYI. Please notice them
